//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiThi
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string MaHD { get; set; }
        public string Manhanvien { get; set; }
        public Nullable<System.DateTime> Ngayban { get; set; }
        public string Makhach { get; set; }
        public Nullable<double> Tongtien { get; set; }
    
        public virtual CHITIETHOADON CHITIETHOADON { get; set; }
        public virtual KHACHANG KHACHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
